// ------------------------------------------
//  Created by Jean-Michel Bruel on 2019-12.
//  Copyright (c) 2019 IRIT/U. Toulouse. All rights reserved.
// Thanks to Louis Chanouha for code & idea
// ------------------------------------------
= BUT-Info/S5.A.01 : Développement avancé
Jean-Michel Bruel
v23.1, {localdate}
:mailto: jbruel@gmail.com
:status: bottom
:inclusion:
:experimental:
:toc: toc2
:icons: font
:window: _blank
:asciidoctorlink: link:http://asciidoctor.org/[Asciidoctor]indexterm:[Asciidoctor]

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/IUT-Blagnac/S5.A.01-template.git

// Tags
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente uen des parties du projet à développer dans le cadre de la SAÉ 5.A.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné par ailleurs.
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/S5.A.01-template.git. 

== Équipe

Projet est réalisé par::

- https://github.com/janeDoe[Jane Doe]
- https://github.com/johnSmith[John Smith]
...


== Contexte général


TIP: En cas de besoin, n'hésitez pas à me contacter (jean-michel.bruel@univ-tlse2.fr) ou à me poser des questions via le Discord de l'IUT.
