export enum SAEStatus {
  PENDING_USERS = "PENDING_USERS",
  PENDING_WISHES = "PENDING_WISHES",
  LAUNCHED = "LAUNCHED",
  LAUNCHED_OPEN_FOR_INTERNSHIP = "LAUNCHED_OPEN_FOR_INTERNSHIP",
  CLOSED = "CLOSED",
}
