export enum SAEStatus {
  PENDING_USERS = "PENDING_USERS",
  PENDING_WISHES = "PENDING_WISHES",
  LAUNCHED = "LAUNCHED",
  LAUNCHED_OPEN_FOR_ALTERNANTS = "LAUNCHED_OPEN_FOR_ALTERNANTS",
  CLOSED = "CLOSED",
}
